### ISSUE TITLE
Crash into RecyclerView

### ISSUE THREAD

**Issue by igorka48** [RamiJ3mli/PercentageChartView#15]
I had added ChartView into recycler's cell and received crash on cell updating. 
`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ramijemli.percentagechartview.renderer.BaseModeRenderer.measure(int, int, int, int, int, int)' on a null object reference
        at com.ramijemli.percentagechartview.PercentageChartView.onMeasure(PercentageChartView.java:130)
        at android.view.View.layout(View.java:15583)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
        at android.view.View.layout(View.java:15596)
        at android.view.ViewGroup.layout(ViewGroup.java:4966)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9464)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1685)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1391)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1128)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1843)
        at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1942)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3297)
        at android.view.View.dispatchTouchEvent(View.java:8388)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
        at android.view.View.dispatchPointerEvent(View.java:8578)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:35`

xml: 
` <com.ramijemli.percentagechartview.PercentageChartView
                android:id="@+id/dogProgressView"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:layout_marginRight="10dp"
                app:pcv_mode="ring"
                app:pcv_orientation="counter_clockwise"
                app:pcv_animDuration="400"
                app:pcv_textColor="@color/darkGray"
                app:pcv_textSize="10sp"
                app:pcv_animInterpolator="linear"
                app:pcv_backgroundBarColor="@color/peachyPinkTranparent"
                app:pcv_progressColor="@color/peachyPink"
                app:pcv_textStyle="bold"
                app:pcv_progressBarThickness="4dp"
                app:pcv_backgroundBarThickness="4dp"
                app:pcv_startAngle="135"/>`

First time Chart draws as expected but crash performs on cell updating. 
Tested on API 28 and 21.

**Comment by varun508** [comment]
I have the same issue. Any solution?

**Comment by igorka48** [comment]
I found temporary workaround by removing PercentageChartView in onViewDetachedFromWindow and adding in  onViewAttachedToWindow. But It lose state and you need keep in manually. 
  ```
  override fun onViewDetachedFromWindow(holder: HomeAdapterHolder) {
        holder.onViewDetachedFromWindow()
        super.onViewDetachedFromWindow(holder)
    }

    override fun onViewAttachedToWindow(holder: HomeAdapterHolder) {
        super.onViewAttachedToWindow(holder)
        holder.onViewAttachedToWindow()
    }
```

I hope that @RamiJ3mli will find more elegant solution

**Comment by HariharanEswaran** [comment]
Am also have that issue.Any fix for that?

**Comment by NoahReyson** [comment]
Same.

No answer yet ?

**Comment by emilpedersen** [comment]
Same here :/

**Comment by arpitsingh21** [comment]
same issue

**Comment by mv03790** [comment]
Same issues

**Comment by eggham0518** [comment]
same

**Comment by ajjubhai** [comment]
i am having same issue .please help

**Comment by ajjubhai** [comment]
any solution yet ??

**Comment by hazemzuhair** [comment]
Help , same issue

**Comment by koral--** [comment]
Here is my workaround: https://jitpack.io/#DroidsOnRoids/PercentageChartView/5a6836bd0d

PS
Comments like:
> I have the same issue

won't help anybody.
