### ISSUE TITLE
App crashed on android 9

### ISSUE THREAD

**Issue by shree-vastava** [RamiJ3mli/PercentageChartView#19]
Hi This is my xml. My app is crashing on launch itself. I did not check it on other versions but on Pie, it is crashing

`
<com.ramijemli.percentagechartview.PercentageChartView
                    android:id="@+id/percentage_university"
                    android:layout_width="@dimen/one_hundred_dp"
                    android:layout_height="@dimen/one_hundred_dp"
                    android:layout_marginTop="@dimen/twenty_dp"
                    app:pcv_mode="ring"
                    app:pcv_orientation="clockwise"
                    app:pcv_animDuration="800"
                    app:pcv_animInterpolator="anticipate_overshoot"
                    app:pcv_progress="69"
                    app:pcv_gradientColors="#FFFFFF,#DA9393,#D5A9A9"
                    app:pcv_gradientType="linear"
                    app:pcv_backgroundBarColor="#C97E7E"
                    app:pcv_backgroundBarThickness="@dimen/three_dp"
                    app:pcv_progressBarThickness="@dimen/ten_dp"
                    app:pcv_startAngle="270"/>
`

and this is the error I  am getting

`android.view.InflateException: Binary XML file line #79: Binary XML file line #79: Error inflating class com.ramijemli.percentagechartview.PercentageChartView
    Caused by: android.view.InflateException: Binary XML file line #79: Error inflating class com.ramijemli.percentagechartview.PercentageChartView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.acoustech.prakharportfolio.view.education.EducationFragment.onCreateView(EducationFragment.kt:18)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2669)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1321)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2515)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2290)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2246)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2143)
        at androidx.fragment.app.FragmentManager$3.run(FragmentManager.java:417)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.ramijemli.percentagechartview.renderer.BaseModeRenderer.setup(BaseModeRenderer.java:387)
        at com.ramijemli.percentagechartview.renderer.RingModeRenderer.setup(RingModeRenderer.java:114)
        at com.ramijemli.percentagechartview.renderer.RingModeRenderer.<init>(RingModeRenderer.java:72)
        at com.ramijemli.percentagechartview.PercentageChartView.init(PercentageChartView.java:139)
        at com.ramijemli.percentagechartview.PercentageChartView.<init>(PercentageChartView.java:112)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.acoustech.prakharportfolio.view.education.EducationFragment.onCreateView(EducationFragment.kt:18) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2669) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1321) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028) 
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346) 
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2515) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2290) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2246) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2143) 
        at androidx.fragment.app.FragmentManager$3.run(FragmentManager.java:417) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.ramijemli.percentagechartview.renderer.BaseModeRenderer.setup(BaseModeRenderer.java:387) 
        at com.ramijemli.percentagechartview.renderer.RingModeRenderer.setup(RingModeRenderer.java:114) 
        at com.ramijemli.percentagechartview.renderer.RingModeRenderer.<init>(RingModeRenderer.java:72) 
        at com.ramijemli.percentagechartview.PercentageChartView.init(PercentageChartView.java:139) 
        at com.ramijemli.percentagechartview.PercentageChartView.<init>(PercentageChartView.java:112) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.acoustech.prakharportfolio.view.education.EducationFragment.onCreateView(EducationFragment.kt:18) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2669) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1321) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028) 
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346) 
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2515) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2290) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2246) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2143) 
        at androidx.fragment.app.FragmentManager$3.run(FragmentManager.java:417) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**Comment by developerbrainiton3** [comment]
having same problem 
Error inflating class com.ramijemli.percentagechartview.PercentageChartView

**Comment by ponomol1263** [comment]
having same problem
